### ISSUE TITLE
Data for eval.py script

### ISSUE THREAD

**Issue by VolodymyrAhafonov** [QLYoo/LFPNet#3]
Hello, 
very interesting paper and promising results!
Could you please provide test data for `eval.py.` 
I want to try out your matting network.

Kind regards, 
Vladimir.

**Comment by Windaway** [comment]
You can create three folders _merged_, _trimap_, and _alpha_, then put images in folders _merged_ and _trimap_. 
LFPNet works better on high-resolution images.

**Comment by Windaway** [comment]
Thank you for your feedback. The code runs normally on my computer and training server. Below are the test images (no ground truth) and our results. I think the code may depend on a specific version of the python library. You may build a new environment according to my configuration.

![doll](https://user-images.githubusercontent.com/4530735/136026214-6d865910-ca88-44a8-8a6c-b1a32f2ccb7f.png)
![doll](https://user-images.githubusercontent.com/4530735/136026194-3f1e5aac-f393-49cc-ab1d-91d48d3ec142.png)
![image](https://user-images.githubusercontent.com/4530735/136024058-80615026-2442-439e-ac77-59af581c9809.png)

> 
> absl-py==0.9.0
> addict==2.4.0
> apturl==0.5.2
> asn1crypto==0.24.0
> astor==0.8.0
> attrs==19.3.0
> backcall==0.1.0
> beautifulsoup4==4.6.0
> bleach==3.1.0
> Brlapi==0.6.6
> certifi==2018.1.18
> chardet==3.0.4
> chumpy==0.69
> Click==7.0
> codecov==2.1.11
> colorama==0.4.4
> command-not-found==0.3
> ConfigArgParse==0.15.1
> configer==1.4.1
> configparser==4.0.2
> coverage==5.5
> cryptography==2.1.4
> cupshelpers==1.0
> cycler==0.10.0
> Cython==0.29.14
> decorator==4.4.1
> defer==1.0.6
> defusedxml==0.6.0
> distro-info===0.18ubuntu0.18.04.1
> entrypoints==0.3
> flake8==3.8.4
> freetype-py==2.1.0.post1
> future==0.18.2
> gast==0.3.2
> grpcio==1.25.0
> h5py==2.7.1
> homogenus===.5
> html5lib==0.999999999
> httplib2==0.9.2
> human-body-prior==0.9.3.0
> idna==2.6
> imageio==2.6.1
> imageio-ffmpeg==0.3.0
> imgaug==0.4.0
> importlib-metadata==0.23
> iniconfig==1.1.1
> interrogate==1.3.2
> ipykernel==5.1.3
> ipython==7.9.0
> ipython-genutils==0.2.0
> ipywidgets==7.5.1
> isort==4.3.21
> jedi==0.15.1
> Jinja2==2.10.3
> jsonpatch==1.25
> jsonpointer==2.0
> jsonschema==3.1.1
> jupyter-client==5.3.4
> jupyter-core==4.6.1
> Keras-Applications==1.0.8
> Keras-Preprocessing==1.1.0
> keyring==10.6.0
> keyrings.alt==3.0
> kiwisolver==1.1.0
> kornia==0.4.0
> language-selector==0.1
> launchpadlib==1.10.6
> lazr.restfulclient==0.13.5
> lazr.uri==1.0.3
> leveldb==0.1
> llvmlite==0.32.1
> lmdb==1.1.1
> louis==3.5.0
> lxml==4.2.1
> macaroonbakery==1.1.3
> Mako==1.0.7
> Markdown==3.1.1
> MarkupSafe==1.1.1
> matplotlib==3.1.2
> mccabe==0.6.1
> mesh-intersection==0.1.0
> mistune==0.8.4
> mmcv-full==1.2.6
> -e git+https://gitee.com/mirrors/mmdetection.git@247785ceb31cabb0e3fd4c6ce17108d04f478ab8#egg=mmdet
> -e git+https://github.com/open-mmlab/mmediting.git@4c2345f6daa57ecb87f5fdb3c8e0ffa60993d83c#egg=mmedit
> mmpycocotools==12.0.3
> mock==3.0.5
> more-itertools==7.2.0
> moviepy==1.0.1
> nbconvert==5.6.1
> nbformat==4.4.0
> netifaces==0.10.4
> networkx==2.4
> nose==1.3.7
> notebook==6.0.2
> numba==0.49.1
> numexpr==2.6.4
> numpy==1.17.4
> oauth==1.0.1
> olefile==0.45.1
> open3d-python==0.7.0.0
> opencv-python==4.2.0.34
> opendr==0.78
> packaging==20.9
> pandas==0.22.0
> pandocfilters==1.4.2
> parso==0.5.1
> pexpect==4.7.0
> pickleshare==0.7.5
> Pillow==6.2.2
> pluggy==0.13.1
> proglog==0.1.9
> prometheus-client==0.7.1
> prompt-toolkit==2.0.10
> protobuf==3.11.2
> ptyprocess==0.6.0
> py==1.10.0
> pycairo==1.16.2
> pycocotools==2.0.0
> pycodestyle==2.6.0
> pycrypto==2.6.1
> pycups==1.9.73
> pyflakes==2.2.0
> pyglet==1.4.0b1
> Pygments==2.4.2
> pygobject==3.26.1
> pymacaroons==0.13.0
> PyMatting==1.0.6
> PyNaCl==1.1.2
> PyOpenGL==3.1.0
> pyparsing==2.4.6
> pyrender==0.1.32
> pyRFC3339==1.0
> pyrsistent==0.15.5
> pytest==6.2.2
> pytest-runner==5.3.0
> python-apt==1.6.5+ubuntu0.5
> python-dateutil==2.8.1
> python-debian==0.1.32
> python-gflags==1.5.1
> pythotk==0.2
> pytz==2018.3
> PyWavelets==1.1.1
> pyxdg==0.25
> PyYAML==5.1
> pyzmq==18.1.0
> reportlab==3.4.0
> requests==2.18.4
> requests-unixsocket==0.1.5
> scikit-image==0.16.2
> scikit-learn==0.20.3
> scipy==1.3.2
> screen-resolution-extra==0.0.0
> SecretStorage==2.3.1
> Send2Trash==1.5.0
> Shapely==1.6.4.post2
> simplegeneric==0.8.1
> simplejson==3.13.2
> six==1.13.0
> smplx==0.1.13
> system-service==0.3
> systemd-python==234
> tables==3.4.2
> tabulate==0.8.9
> tensorboard==1.13.1
> tensorboardX==2.0
> tensorflow==1.13.1
> tensorflow-estimator==1.13.0
> termcolor==1.1.0
> terminado==0.8.3
> terminaltables==3.1.0
> testpath==0.4.4
> toml==0.10.2
> torch==1.6.0
> torchfile==0.1.0
> torchgeometry==0.1.2
> torchnet==0.0.5.1
> torchsummary==1.5.1
> torchvision==0.7.0
> tornado==6.0.3
> tqdm==4.38.0
> traitlets==4.3.3
> transforms3d==0.3.1
> trimesh==3.4.1
> ubuntu-drivers-common==0.0.0
> ufw==0.36
> unattended-upgrades==0.1
> urllib3==1.22
> usb-creator==0.3.3
> visdom==0.1.8.9
> wadllib==1.3.2
> wcwidth==0.1.7
> webencodings==0.5.1
> websocket-client==0.57.0
> Werkzeug==0.16.0
> widgetsnbextension==3.5.1
> xkit==0.0.0
> yacs==0.1.7
> yapf==0.30.0
> youtube-dl==2019.11.5
> zipp==0.6.0
> zope.interface==4.3.2
>

**Comment by Windaway** [comment]
Here is the result of FBAMatting.
![image](https://user-images.githubusercontent.com/4530735/136027259-114290ff-3e77-46cd-9337-3b2ef5f8ccca.png)

**Comment by Windaway** [comment]
Here is another HR real-world image (no ground truth), I think it will be helpful to you.
RGB:
![image](https://user-images.githubusercontent.com/4530735/136032204-dfa21d55-f16f-4b87-aa59-54f62cb7e42c.png)
Trimap:
![image](https://user-images.githubusercontent.com/4530735/136032187-c3858aff-2545-497d-a337-2e22f72d2aa4.png)
LFPNet:
![image](https://user-images.githubusercontent.com/4530735/136032240-ca99416e-8eaa-4f68-828d-21e26a648f00.png)
FBAMatting:
![image](https://user-images.githubusercontent.com/4530735/136032525-86ecfd5e-eda4-4280-9e08-8c6fd751f68f.png)
GCAMatting:
![image](https://user-images.githubusercontent.com/4530735/136032569-600af39c-594e-4d6b-98e2-cda9ad68f994.png)
IndexNet:
![image](https://user-images.githubusercontent.com/4530735/136032601-31a3eda8-1b25-49ff-9798-dde0172f2eb5.png)

**Comment by VolodymyrAhafonov** [comment]
@Windaway thank you very much for provided images! I've reproduced same results with provided images. And also found root cause of issue with my data.

**Comment by VolodymyrAhafonov** [comment]
We can close issue now.

**Comment by hackkhai** [comment]
@VolodymyrAhafonov What was the problem that you faced with your data?

**Comment by VolodymyrAhafonov** [comment]
@hackkhai Unknown (grey) area was equal to 127 in my trimap. Eval script expect that unknown area is equal to 128.
