### ISSUE TITLE
Retrieve foreground prediction

### ISSUE THREAD

**Issue by WANGEOGEO** [QLYoo/LFPNet#5]
Hi,
This work looks fantastic and performs well. Recently I have been studying on foreground prediction during matting, but I am not quite sure which part of the code in **eval.py** is about foreground prediction? I would like to visualize those predictions for further study.
Thanks in advance for help!

**Comment by Windaway** [comment]
There is no foreground prediction code in eval.py. You may use the foreground output of the LFPnet defined in model.py. But the predicted foreground is not good.  I think GCAMatting, which uses the module from the inpainting network, may be more suitable for you.

**Comment by Windaway** [comment]
There is a difference between LFPNet and FBAMatting results. LFPNet only estimates the foreground in the unknown regions and the foreground regions, FBAmatting estimates foreground on the entire image.  I think this is why FBAMatting can predict foreground better.

RGB:
![image](https://user-images.githubusercontent.com/4530735/136660470-4ea2d48a-0a20-48bb-a142-2bfff5cf0df6.png)
![image](https://user-images.githubusercontent.com/4530735/136660588-3473051f-a14b-4514-beb2-d2351013ec0b.png)
FBA:
![image](https://user-images.githubusercontent.com/4530735/136660483-b6010452-1ff2-4309-8819-927320bdab46.png)
![image](https://user-images.githubusercontent.com/4530735/136660585-2c1f7856-fd21-4fd0-91ab-d06f3e307219.png)
LFPNet:
![image](https://user-images.githubusercontent.com/4530735/136660439-da4586e4-5764-486f-aa1b-fdcdb3847b47.png)
![image](https://user-images.githubusercontent.com/4530735/136660594-52b8e72b-baec-41a6-85f7-c177a2edf075.png)

**Comment by WANGEOGEO** [comment]
Ah I see ...... Great appreciation on showing some visualizations, now I have a better understanding on the mechanisms.
