### ISSUE TITLE
Paper - code correspondence

### ISSUE THREAD

**Issue by VolodymyrAhafonov** [QLYoo/LFPNet#9]
Hello!
I am trying to compare paper description of neural network and real neural network from this repo.
I've noticed this lines:
```
b,_,_,_=x.shape
setensor=torch.reshape(self.setensor,[b,1024,1,1])
setensor=torch.nn.functional.interpolate(setensor, (feat[-1].shape[2], feat[-1].shape[3]),mode='bilinear',align_corners=False)
featz=self.se1(feat[-1],setensor)
```
Right after context encoder and before `CSPP` module.
According to code it looks like squeeze excitation block, but I don't see any mentions of this block in paper.
Could you please clarify this difference?

Thank you in advance

**Comment by Windaway** [comment]
Yeah, it is a SEBlock and is designed for channel attention.
However, I check the parameters and find that more parameters are of no use. 
XD

**Comment by VolodymyrAhafonov** [comment]
Thank you for quick reply! I have another small question. Do you have a supplementary materials for your paper with detailed layerwise description of neural net structure?

**Comment by Windaway** [comment]
Sorry, no.

**Comment by VolodymyrAhafonov** [comment]
Understood. Thank you for such a quick replies!
